### ISSUE TITLE
Fix UTF-8 symbolism for trade items

### ISSUE THREAD

**Issue by shanebrowncs** [shanebrowncs/Trade-Assistant#1]
Items gathered from trade links are not properly formatted on the page. Fix and commit.

**Comment by shanebrowncs** [comment]
The issue seems to only be happening on the remote server?

**Comment by SajeOne** [comment]
The issue seems to only be happening on the remote server?

**Comment by shanebrowncs** [comment]
Changed DomXPath query result from decoding from HTML to decoding from UTF-8. Ironically now the characters won't display properly on my local server. I guess closed?
